rule all:
    input:
        "../data/processed/merged.h5ad"

rule run_pipeline:
    output:
        "../data/processed/merged.h5ad"
    shell:
        """
        export CUDA_VISIBLE_DEVICES=""
        PYTHONPATH=. python workflows/main.py \
            --config ../config/config_reduction.yaml \
            --mode merge
        """
